name: master_journey
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dio: ^5.3.3
  logger: ^1.1.0
  shared_preferences: ^2.2.2
  image_picker: ^0.8.7+5
  fluttertoast: ^8.1.2
  image: ^3.0.1
  flutter_lints: ^2.0.0
  path_provider: ^2.0.14
  share_plus: ^7.2.1
  flutter_launcher_icons: any
  change_app_package_name: ^1.1.0
  country_pickers: ^2.0.0
  scroll_loop_auto_scroll: ^0.0.2
  shimmer: ^2.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/appicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/image/
    - assets/svg/

